#
# Post settings
#
title: ralismark
excerpt_separator: <!--more-->

kramdown:
  header_offset: 1 # h1 becomes h2 (h1 is title)
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Exclude these files from production
exclude:
  - LICENSE
  - README.md
  - Dockerfile
  - Makefile

# Default values for page frontmatter
defaults:
  -
    scope:
      path: "" # everything
      type: "posts"
    values:
      modules:
        # hlink: true
        math: true

# Use remote theme in prod
plugins:
  - jekyll-remote-theme
remote_theme: ralismark/ralismark.github.io@theme

# vim: set et ts=2:
