#
# site settings
#
title: ralismark
description: Discussions from all depths of computer science
excerpt_separator: <!--more-->

#
# build setting
#
markdown: kramdown
safe: true

kramdown:
  math_engine: mathjax # Forced by github-pages
  # Use Github-flavoured markdown (e.g. triple backtick code)
  input: GFM
  syntax_highlighter: rouge
  header_offset: 1 # h1 becomes h2 (h1 is title)

  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sass generated css
sass:
  style: expanded

# Atom feed config
feed:
  excerpt_only: true

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap
  - jekyll-feed # Create an Atom feed

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Exclude these files from production
exclude:
  - LICENSE
  - README.md
  - Dockerfile
  - Makefile

# Default values for page frontmatter
defaults:
  -
    scope:
      path: "" # everything
      type: "posts"
    values:
      modules:
        # hlink: true
        math: true

# vim: set et ts=2:
