#
# site settings
#
title: ralismark
description: Discussions from all depths of computer science

#
# build setting
#
markdown: kramdown
safe: true

kramdown:
  # Use Github-flavoured markdown (e.g. triple backtick code)
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sass generated css
sass:
  style: expanded

# CSS files to include
css_include: []

# Atom feed config
feed:
  excerpt_only: true

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap
  - jekyll-feed # Create an Atom feed

# vim: set et ts=2:
